# Generated by Django 3.1.5 on 2021-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('content', models.CharField(blank=True, default='Нет описания', max_length=200, null=True, verbose_name='Описание для файла')),
                ('date_pub', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации файла')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['name'],
            },
        ),
    ]
