# Generated by Django 3.1.5 on 2021-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210106_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер файла'),
        ),
    ]
