# Generated by Django 3.1.5 on 2021-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название файла'), max_length=150, null=True, verbose_name='Размер файла'),
        ),
    ]
