# Generated by Django 3.1.5 on 2021-01-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20210106_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(default=0, max_length=150, verbose_name='Размер файла'),
            preserve_default=False,
        ),
    ]
