# Generated by Django 3.1.5 on 2021-01-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210107_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(editable=False, max_length=150, verbose_name='Размер файла'),
        ),
    ]
