# Generated by Django 3.1.5 on 2021-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20210107_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(max_length=150, verbose_name='Размер файла'),
        ),
    ]
