# Generated by Django 3.1.5 on 2021-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20210107_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
