# Generated by Django 3.1.5 on 2021-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20210107_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название файла')),
                ('content', models.CharField(blank=True, default='Нет описания', max_length=200, null=True, verbose_name='Описание для файла')),
                ('date_pub', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации файла')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='Слаг')),
                ('size', models.CharField(max_length=150, verbose_name='Размер файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_pub',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
    ]
