# Generated by Django 3.1.5 on 2021-01-07 17:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20210107_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.CharField(blank=True, default='Нет описания', max_length=200, null=True, verbose_name='Описание для файла'),
        ),
        migrations.AddField(
            model_name='file',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default=datetime.datetime(2021, 1, 7, 17, 59, 29, 611494, tzinfo=utc), max_length=150, verbose_name='Размер файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
