# Generated by Django 3.1.5 on 2021-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20210107_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size_str',
            field=models.CharField(max_length=150, verbose_name='размер'),
        ),
    ]
