# Generated by Django 3.1.5 on 2021-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20210107_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size_str',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='размер'),
        ),
    ]
