# Generated by Django 3.1.5 on 2021-01-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_auto_20210107_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size_str',
        ),
    ]
