# Generated by Django 3.1.5 on 2021-01-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_auto_20210108_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер файла'),
        ),
    ]
