# Generated by Django 3.1.5 on 2021-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_auto_20210108_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=0, unique=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
