# Generated by Django 3.1.5 on 2021-01-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_auto_20210108_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
