# Generated by Django 3.1.5 on 2021-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_auto_20210128_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='max_size_of_files',
            field=models.IntegerField(default=50, editable=False, verbose_name='Максимальный размер для хранения файлов'),
        ),
    ]
