# Generated by Django 3.1.5 on 2021-02-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_auto_20210128_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='engaged_size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Занято места'),
        ),
    ]
