# Generated by Django 3.1.5 on 2021-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0036_auto_20210201_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='correct_size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер файла (в кб)'),
        ),
    ]
