# Generated by Django 3.1.5 on 2021-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0037_auto_20210201_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='correct_size',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (в кб)'),
        ),
    ]
