# Generated by Django 3.1.5 on 2021-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0038_auto_20210201_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='correct_engaged_size',
            field=models.CharField(default=0, editable=False, max_length=150, verbose_name='Занято места'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='engaged_size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Занято места (в кб)'),
        ),
    ]
