# Generated by Django 3.1.5 on 2021-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0039_auto_20210201_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='advuser',
            name='correct_max_size_of_files',
            field=models.CharField(default=0, editable=False, max_length=150, verbose_name='Максимальный размер для хранения файлов'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='max_size_of_files',
            field=models.IntegerField(default=104857600, editable=False, verbose_name='Максимальный размер для хранения файлов (в кб)'),
        ),
    ]
